### Secret
apiVersion: v1
kind: Secret
metadata:
  name: github-action
  namespace: github
type: Opaque
data:
  # Base64 encoded of the token
  ACCESS_TOKEN: <a base64 encoded access token>

---

### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: github-runner
          image: michaelcoll/github-runner:latest
          envFrom:
            - secretRef:
                name: github-action
          env:
            - name: ORG_NAME
              value: your-organization
            - name: ORG_RUNNER
              value: "true"
            - name: LABELS
              value: k8s,docker
          volumeMounts:
            - mountPath: /var/run
              name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run
