apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-docker
  labels:
    app: github-runner-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner-docker
  template:
    metadata:
      labels:
        app: github-runner-docker
    spec:
      containers:
      - name: github-runner-docker
        image: sgryczan/github-runner:dood
        imagePullPolicy: Always
        env:
        - name: GITHUB_OWNER
          value: my-org
        - name: GITHUB_REPOSITORY
          value: my-repo
        - name: RUNNER_LABELS
          value: k8s,docker
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github
              key: pat
        volumeMounts: 
          - mountPath: /var/run 
            name: docker-sock
      volumes: 
        - name: docker-sock 
          hostPath: 
              path: /var/run 
