name: Build
on:
  push:
    paths-ignore:
      - deployment.yml
      - README.md
    tags-ignore:
      - '*'
    branches:
      - master
  schedule:
    - cron: '20 10 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build . -t michaelcoll/github-runner:latest

      - name: Push
        run: docker push michaelcoll/github-runner
