name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get GitHub organization or user
        run: echo "ORG=$(dirname ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
      - name: Get current tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: docker build . -t ${ORG}/github-runner:${TAG} -t ${ORG}/github-runner:latest

      - name: Push
        run: docker push ${ORG}/github-runner
